# Generated by Django 3.2 on 2022-11-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221102_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(
                blank=True, null=True, to='recipes.Tag', verbose_name='tag'),
        ),
    ]
