name: CI/CD foodgram

on: push

jobs:
  tests:
    name: Flake8 and pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install -r backend/requirements.txt --upgrade pip --use-pep517
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
    - name: Test with flake8
      run: python -m flake8
    - name: Test with pytest
      run: pytest