name: CI/CD foodgram

on: push

jobs:
  tests:
    name: Flake8 and pytest
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Setup python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.7
    - 
      name: Install dependencies
      run: |
        python -m pip install -r backend/requirements.txt --upgrade pip --use-pep517
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
    - 
      name: Test with flake8
      run: python -m flake8
    - 
      name: Test with pytest
      run: pytest
  build:
    name: Build and push images
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }} 
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/foodgram_backend:latest